### ISSUE TITLE
crash when rendering armor

### ISSUE THREAD

**Issue by AnAwesomGuy** [shizotoaster/ForgedAPIFork#1]
so i was lagging in the modpack, so i tried to add enhanced block entities, which depends on this mod. whenever i went into third person or opened my inventory, i would crash, due to a npe in [one of the mixins](https://github.com/shizotoaster/ForgedAPIFork/blob/main/src/main/java/net/fabricmc/fabric/mixin/client/rendering/MixinArmorFeatureRenderer.java#L83-L93)
it seems like its due to an incompatibility with draconic evolution, maybe add a null check?
i think you should probably also embed this with only the necessary parts into enhanced block entities, so there's no need for another dependency and also preventing crashes like this
[crash report here](https://github.com/shizotoaster/ForgedAPIFork/files/14059506/crash-2024-01-25_21.42.46-client.txt)

**Comment by shizotoaster** [comment]
Confirmed, crash occurs when armor piece is rendered on entity
